Repository boostcamp-2020/IssueTracker-21, pull requests merged in 2020-11, with the labels that each got.

#62 Feat/FE-Editor
  Client/src/components/Editor/Editor.jsx
  Client/src/components/Editor/index.js
Labels: Front-End

#67 Feat/FE- editor
  Client/src/components/Editor/Editor.jsx
  Client/src/utils/uploadImgur.js
Labels: Feature, Front-End

#86 Feat/FE,BE register modal, 회원가입 기능 구현
  Client/src/components/Editor/Editor.jsx
  Client/src/components/RegisterModal/RegisterModal.jsx
  Client/src/components/RegisterModal/index.js
  Client/src/utils/uploadImgur.js
  Client/src/views/LoginPage/LoginPage.jsx
  Client/src/views/LoginPage/style.css
  Server/controllers/userController.js
Labels: Feature, Front-End

#89 [BE] Feat: 마일스톤 정보 열람 시 오픈 / 클로즈된 이슈 개수도 가져오도록 변경
  Server/controllers/milestoneController.js
  Server/dao/milestoneDao.js
Labels: Back-End
